swagger: '2.0'
info:
  version: 1.0.0
  title: Bookings API
tags:
  - name: Bookings
    description: The Bookings managing API
paths:
  /bookings:
    get:
      tags:
        - Bookings
      summary: Get all bookings for a user
      responses:
        '200':
          description: A list of bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
        '500':
          description: Server error
    post:
      tags:
        - Bookings
      summary: Create a new booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '201':
          description: Booking created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '500':
          description: Server error
  /bookings/{id}:
    get:
      tags:
        - Bookings
      summary: Get a specific booking by id
      parameters:
        - name: id
          in: path
          required: true
          description: The Booking id
          schema:
            type: string
      responses:
        '200':
          description: The Booking description by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '404':
          description: Booking not found
        '500':
          description: Server error
    put:
      tags:
        - Bookings
      summary: Update a specific booking by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The Booking id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '200':
          description: Booking updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '404':
          description: Booking not found
        '500':
          description: Server error
    delete:
      tags:
        - Bookings
      summary: Delete a specific booking
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          description: The booking id
      responses:
        '200':
          description: Booking deleted
        '404':
          description: Booking not found
        '500':
          description: Server error
  /bookings/admin:
    get:
      summary: Get all bookings for an admin
      responses:
        '200':
          description: A list of bookings
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Booking'
        '500':
          description: Server error
    put:
      summary: Update any booking
      responses:
        '200':
          description: Booking updated
          schema:
            $ref: '#/components/schemas/Booking'
        '500':
          description: Server error
    delete:
      summary: Delete any booking
      responses:
        '200':
          description: Booking deleted
        '500':
          description: Server error
components:
  schemas: 
    Booking:
      type: object
      properties:
        apptDate:
          type: array
          items:
            type: string
            format: date-time
        user:
          type: string
        campground:
          type: string
        createAt:
          type: string
          format: date-time
      example:
        apptDate: ['2020-01-01T00:00:00Z','2020-01-03T00:00:00Z']
        user: 'user1'
        campground: 'campground1'
        createAt: '2020-01-01T00:00:00Z'

  
